### ISSUE TITLE
Fatal error while combining xk6-browser and xk6-cache

### ISSUE THREAD

**Issue by anslei** [szkiba/xk6bundler#1]
C:\Users\_pseudo_>xk6bundler --with github.com/grafana/xk6-browser --with github.com/szkiba/xk6-cache
2022/06/10 12:48:21 [INFO] Temporary folder: C:\Users\ASLEIL~1\AppData\Local\Temp\buildenv_2022-06-10-1248.918629070
2022/06/10 12:48:21 [INFO] Initializing Go module
2022/06/10 12:48:21 [INFO] exec (timeout=10s): C:\Program Files\Go\bin\go.exe mod init k6
go: creating new go.mod: module k6
2022/06/10 12:48:21 [INFO] Pinning versions
2022/06/10 12:48:21 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod edit -require github.com/grafana/xk6-browser@latest
2022/06/10 12:48:21 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -compat=1.17
go: finding module for package github.com/fsnotify/fsnotify
go: finding module for package gopkg.in/tomb.v1
go: found gopkg.in/tomb.v1 in gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: found github.com/fsnotify/fsnotify in github.com/fsnotify/fsnotify v1.5.4
2022/06/10 12:48:22 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod edit -require github.com/szkiba/xk6-cache@latest
2022/06/10 12:48:22 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -compat=1.17
go: finding module for package go.k6.io/k6/stats
k6 imports
        github.com/szkiba/xk6-cache imports
        go.k6.io/k6/stats: module go.k6.io/k6@latest found (v0.38.3), but does not contain package go.k6.io/k6/stats
2022/06/10 12:48:23 [INFO] Cleaning up temporary folder: C:\Users\pseudo\AppData\Local\Temp\buildenv_2022-06-10-1248.918629070
2022/06/10 12:48:23 [FATAL] exit status 1

I am getting the following log when trying to combine the two extensions. Any idea how to fix it? Thank you for assistance

**Comment by colymore** [comment]
Hi. This is a problem with the version of the cache extension, which is not adapted to the last version of k6 modules. Surely there is a pull request to update it.

**Comment by szkiba** [comment]
fixed in xk6-cache v0.2.0
